// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Record.proto

package com.kanven.conveyor.entity;

public final class RecordProto {
  private RecordProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kanven.conveyor.entity.Record)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 batchId = 1;</code>
     */
    long getBatchId();

    /**
     * <code>repeated bytes entities = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getEntitiesList();
    /**
     * <code>repeated bytes entities = 2;</code>
     */
    int getEntitiesCount();
    /**
     * <code>repeated bytes entities = 2;</code>
     */
    com.google.protobuf.ByteString getEntities(int index);
  }
  /**
   * Protobuf type {@code com.kanven.conveyor.entity.Record}
   */
  public  static final class Record extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kanven.conveyor.entity.Record)
      RecordOrBuilder {
    // Use Record.newBuilder() to construct.
    private Record(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Record() {
      batchId_ = 0L;
      entities_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Record(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              batchId_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                entities_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              entities_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          entities_ = java.util.Collections.unmodifiableList(entities_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kanven.conveyor.entity.RecordProto.internal_static_com_kanven_conveyor_entity_Record_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kanven.conveyor.entity.RecordProto.internal_static_com_kanven_conveyor_entity_Record_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kanven.conveyor.entity.RecordProto.Record.class, com.kanven.conveyor.entity.RecordProto.Record.Builder.class);
    }

    private int bitField0_;
    public static final int BATCHID_FIELD_NUMBER = 1;
    private long batchId_;
    /**
     * <code>optional int64 batchId = 1;</code>
     */
    public long getBatchId() {
      return batchId_;
    }

    public static final int ENTITIES_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> entities_;
    /**
     * <code>repeated bytes entities = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getEntitiesList() {
      return entities_;
    }
    /**
     * <code>repeated bytes entities = 2;</code>
     */
    public int getEntitiesCount() {
      return entities_.size();
    }
    /**
     * <code>repeated bytes entities = 2;</code>
     */
    public com.google.protobuf.ByteString getEntities(int index) {
      return entities_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (batchId_ != 0L) {
        output.writeInt64(1, batchId_);
      }
      for (int i = 0; i < entities_.size(); i++) {
        output.writeBytes(2, entities_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (batchId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, batchId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < entities_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(entities_.get(i));
        }
        size += dataSize;
        size += 1 * getEntitiesList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kanven.conveyor.entity.RecordProto.Record)) {
        return super.equals(obj);
      }
      com.kanven.conveyor.entity.RecordProto.Record other = (com.kanven.conveyor.entity.RecordProto.Record) obj;

      boolean result = true;
      result = result && (getBatchId()
          == other.getBatchId());
      result = result && getEntitiesList()
          .equals(other.getEntitiesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + BATCHID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBatchId());
      if (getEntitiesCount() > 0) {
        hash = (37 * hash) + ENTITIES_FIELD_NUMBER;
        hash = (53 * hash) + getEntitiesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kanven.conveyor.entity.RecordProto.Record parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.conveyor.entity.RecordProto.Record parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.conveyor.entity.RecordProto.Record parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.conveyor.entity.RecordProto.Record parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.conveyor.entity.RecordProto.Record parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.conveyor.entity.RecordProto.Record parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.conveyor.entity.RecordProto.Record parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kanven.conveyor.entity.RecordProto.Record parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.conveyor.entity.RecordProto.Record parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.conveyor.entity.RecordProto.Record parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kanven.conveyor.entity.RecordProto.Record prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kanven.conveyor.entity.Record}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kanven.conveyor.entity.Record)
        com.kanven.conveyor.entity.RecordProto.RecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kanven.conveyor.entity.RecordProto.internal_static_com_kanven_conveyor_entity_Record_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kanven.conveyor.entity.RecordProto.internal_static_com_kanven_conveyor_entity_Record_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kanven.conveyor.entity.RecordProto.Record.class, com.kanven.conveyor.entity.RecordProto.Record.Builder.class);
      }

      // Construct using com.kanven.conveyor.entity.RecordProto.Record.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        batchId_ = 0L;

        entities_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kanven.conveyor.entity.RecordProto.internal_static_com_kanven_conveyor_entity_Record_descriptor;
      }

      public com.kanven.conveyor.entity.RecordProto.Record getDefaultInstanceForType() {
        return com.kanven.conveyor.entity.RecordProto.Record.getDefaultInstance();
      }

      public com.kanven.conveyor.entity.RecordProto.Record build() {
        com.kanven.conveyor.entity.RecordProto.Record result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kanven.conveyor.entity.RecordProto.Record buildPartial() {
        com.kanven.conveyor.entity.RecordProto.Record result = new com.kanven.conveyor.entity.RecordProto.Record(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.batchId_ = batchId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          entities_ = java.util.Collections.unmodifiableList(entities_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.entities_ = entities_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kanven.conveyor.entity.RecordProto.Record) {
          return mergeFrom((com.kanven.conveyor.entity.RecordProto.Record)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kanven.conveyor.entity.RecordProto.Record other) {
        if (other == com.kanven.conveyor.entity.RecordProto.Record.getDefaultInstance()) return this;
        if (other.getBatchId() != 0L) {
          setBatchId(other.getBatchId());
        }
        if (!other.entities_.isEmpty()) {
          if (entities_.isEmpty()) {
            entities_ = other.entities_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureEntitiesIsMutable();
            entities_.addAll(other.entities_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kanven.conveyor.entity.RecordProto.Record parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kanven.conveyor.entity.RecordProto.Record) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long batchId_ ;
      /**
       * <code>optional int64 batchId = 1;</code>
       */
      public long getBatchId() {
        return batchId_;
      }
      /**
       * <code>optional int64 batchId = 1;</code>
       */
      public Builder setBatchId(long value) {
        
        batchId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 batchId = 1;</code>
       */
      public Builder clearBatchId() {
        
        batchId_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> entities_ = java.util.Collections.emptyList();
      private void ensureEntitiesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          entities_ = new java.util.ArrayList<com.google.protobuf.ByteString>(entities_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes entities = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getEntitiesList() {
        return java.util.Collections.unmodifiableList(entities_);
      }
      /**
       * <code>repeated bytes entities = 2;</code>
       */
      public int getEntitiesCount() {
        return entities_.size();
      }
      /**
       * <code>repeated bytes entities = 2;</code>
       */
      public com.google.protobuf.ByteString getEntities(int index) {
        return entities_.get(index);
      }
      /**
       * <code>repeated bytes entities = 2;</code>
       */
      public Builder setEntities(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEntitiesIsMutable();
        entities_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes entities = 2;</code>
       */
      public Builder addEntities(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEntitiesIsMutable();
        entities_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes entities = 2;</code>
       */
      public Builder addAllEntities(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureEntitiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entities_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes entities = 2;</code>
       */
      public Builder clearEntities() {
        entities_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.kanven.conveyor.entity.Record)
    }

    // @@protoc_insertion_point(class_scope:com.kanven.conveyor.entity.Record)
    private static final com.kanven.conveyor.entity.RecordProto.Record DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kanven.conveyor.entity.RecordProto.Record();
    }

    public static com.kanven.conveyor.entity.RecordProto.Record getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Record>
        PARSER = new com.google.protobuf.AbstractParser<Record>() {
      public Record parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Record(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Record> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Record> getParserForType() {
      return PARSER;
    }

    public com.kanven.conveyor.entity.RecordProto.Record getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kanven_conveyor_entity_Record_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kanven_conveyor_entity_Record_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Record.proto\022\032com.kanven.conveyor.enti" +
      "ty\"+\n\006Record\022\017\n\007batchId\030\001 \001(\003\022\020\n\010entitie" +
      "s\030\002 \003(\014B\rB\013RecordProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_kanven_conveyor_entity_Record_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kanven_conveyor_entity_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kanven_conveyor_entity_Record_descriptor,
        new java.lang.String[] { "BatchId", "Entities", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
