// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RowEntity.proto

package com.kanven.conveyor.entity;

public final class RowEntityProto {
  private RowEntityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RowEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kanven.conveyor.entity.RowEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string db = 1;</code>
     */
    java.lang.String getDb();
    /**
     * <code>optional string db = 1;</code>
     */
    com.google.protobuf.ByteString
        getDbBytes();

    /**
     * <code>optional string table = 2;</code>
     */
    java.lang.String getTable();
    /**
     * <code>optional string table = 2;</code>
     */
    com.google.protobuf.ByteString
        getTableBytes();

    /**
     * <code>optional string primaryKey = 3;</code>
     */
    java.lang.String getPrimaryKey();
    /**
     * <code>optional string primaryKey = 3;</code>
     */
    com.google.protobuf.ByteString
        getPrimaryKeyBytes();

    /**
     * <code>optional int32 operation = 4;</code>
     */
    int getOperation();

    /**
     * <code>optional int64 time = 5;</code>
     */
    long getTime();

    /**
     * <code>map&lt;string, string&gt; kvs = 6;</code>
     */
    int getKvsCount();
    /**
     * <code>map&lt;string, string&gt; kvs = 6;</code>
     */
    boolean containsKvs(
        java.lang.String key);
    /**
     * Use {@link #getKvsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getKvs();
    /**
     * <code>map&lt;string, string&gt; kvs = 6;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getKvsMap();
    /**
     * <code>map&lt;string, string&gt; kvs = 6;</code>
     */

    java.lang.String getKvsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; kvs = 6;</code>
     */

    java.lang.String getKvsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.kanven.conveyor.entity.RowEntity}
   */
  public  static final class RowEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kanven.conveyor.entity.RowEntity)
      RowEntityOrBuilder {
    // Use RowEntity.newBuilder() to construct.
    private RowEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RowEntity() {
      db_ = "";
      table_ = "";
      primaryKey_ = "";
      operation_ = 0;
      time_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RowEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              db_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              table_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              primaryKey_ = s;
              break;
            }
            case 32: {

              operation_ = input.readInt32();
              break;
            }
            case 40: {

              time_ = input.readInt64();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                kvs_ = com.google.protobuf.MapField.newMapField(
                    KvsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000020;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              kvs = input.readMessage(
                  KvsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              kvs_.getMutableMap().put(kvs.getKey(), kvs.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kanven.conveyor.entity.RowEntityProto.internal_static_com_kanven_conveyor_entity_RowEntity_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetKvs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kanven.conveyor.entity.RowEntityProto.internal_static_com_kanven_conveyor_entity_RowEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kanven.conveyor.entity.RowEntityProto.RowEntity.class, com.kanven.conveyor.entity.RowEntityProto.RowEntity.Builder.class);
    }

    private int bitField0_;
    public static final int DB_FIELD_NUMBER = 1;
    private volatile java.lang.Object db_;
    /**
     * <code>optional string db = 1;</code>
     */
    public java.lang.String getDb() {
      java.lang.Object ref = db_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        db_ = s;
        return s;
      }
    }
    /**
     * <code>optional string db = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDbBytes() {
      java.lang.Object ref = db_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        db_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TABLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object table_;
    /**
     * <code>optional string table = 2;</code>
     */
    public java.lang.String getTable() {
      java.lang.Object ref = table_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        table_ = s;
        return s;
      }
    }
    /**
     * <code>optional string table = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTableBytes() {
      java.lang.Object ref = table_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        table_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIMARYKEY_FIELD_NUMBER = 3;
    private volatile java.lang.Object primaryKey_;
    /**
     * <code>optional string primaryKey = 3;</code>
     */
    public java.lang.String getPrimaryKey() {
      java.lang.Object ref = primaryKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        primaryKey_ = s;
        return s;
      }
    }
    /**
     * <code>optional string primaryKey = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPrimaryKeyBytes() {
      java.lang.Object ref = primaryKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        primaryKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATION_FIELD_NUMBER = 4;
    private int operation_;
    /**
     * <code>optional int32 operation = 4;</code>
     */
    public int getOperation() {
      return operation_;
    }

    public static final int TIME_FIELD_NUMBER = 5;
    private long time_;
    /**
     * <code>optional int64 time = 5;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int KVS_FIELD_NUMBER = 6;
    private static final class KvsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.kanven.conveyor.entity.RowEntityProto.internal_static_com_kanven_conveyor_entity_RowEntity_KvsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> kvs_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetKvs() {
      if (kvs_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            KvsDefaultEntryHolder.defaultEntry);
      }
      return kvs_;
    }

    public int getKvsCount() {
      return internalGetKvs().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; kvs = 6;</code>
     */

    public boolean containsKvs(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetKvs().getMap().containsKey(key);
    }
    /**
     * Use {@link #getKvsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getKvs() {
      return getKvsMap();
    }
    /**
     * <code>map&lt;string, string&gt; kvs = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getKvsMap() {
      return internalGetKvs().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; kvs = 6;</code>
     */

    public java.lang.String getKvsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetKvs().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; kvs = 6;</code>
     */

    public java.lang.String getKvsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetKvs().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDbBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, db_);
      }
      if (!getTableBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, table_);
      }
      if (!getPrimaryKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, primaryKey_);
      }
      if (operation_ != 0) {
        output.writeInt32(4, operation_);
      }
      if (time_ != 0L) {
        output.writeInt64(5, time_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetKvs().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        kvs = KvsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(6, kvs);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDbBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, db_);
      }
      if (!getTableBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, table_);
      }
      if (!getPrimaryKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, primaryKey_);
      }
      if (operation_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, operation_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, time_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetKvs().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        kvs = KvsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, kvs);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kanven.conveyor.entity.RowEntityProto.RowEntity)) {
        return super.equals(obj);
      }
      com.kanven.conveyor.entity.RowEntityProto.RowEntity other = (com.kanven.conveyor.entity.RowEntityProto.RowEntity) obj;

      boolean result = true;
      result = result && getDb()
          .equals(other.getDb());
      result = result && getTable()
          .equals(other.getTable());
      result = result && getPrimaryKey()
          .equals(other.getPrimaryKey());
      result = result && (getOperation()
          == other.getOperation());
      result = result && (getTime()
          == other.getTime());
      result = result && internalGetKvs().equals(
          other.internalGetKvs());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + DB_FIELD_NUMBER;
      hash = (53 * hash) + getDb().hashCode();
      hash = (37 * hash) + TABLE_FIELD_NUMBER;
      hash = (53 * hash) + getTable().hashCode();
      hash = (37 * hash) + PRIMARYKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPrimaryKey().hashCode();
      hash = (37 * hash) + OPERATION_FIELD_NUMBER;
      hash = (53 * hash) + getOperation();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      if (!internalGetKvs().getMap().isEmpty()) {
        hash = (37 * hash) + KVS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetKvs().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kanven.conveyor.entity.RowEntityProto.RowEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.conveyor.entity.RowEntityProto.RowEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.conveyor.entity.RowEntityProto.RowEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kanven.conveyor.entity.RowEntityProto.RowEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kanven.conveyor.entity.RowEntityProto.RowEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.conveyor.entity.RowEntityProto.RowEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.conveyor.entity.RowEntityProto.RowEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kanven.conveyor.entity.RowEntityProto.RowEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kanven.conveyor.entity.RowEntityProto.RowEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kanven.conveyor.entity.RowEntityProto.RowEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kanven.conveyor.entity.RowEntityProto.RowEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kanven.conveyor.entity.RowEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kanven.conveyor.entity.RowEntity)
        com.kanven.conveyor.entity.RowEntityProto.RowEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kanven.conveyor.entity.RowEntityProto.internal_static_com_kanven_conveyor_entity_RowEntity_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetKvs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableKvs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kanven.conveyor.entity.RowEntityProto.internal_static_com_kanven_conveyor_entity_RowEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kanven.conveyor.entity.RowEntityProto.RowEntity.class, com.kanven.conveyor.entity.RowEntityProto.RowEntity.Builder.class);
      }

      // Construct using com.kanven.conveyor.entity.RowEntityProto.RowEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        db_ = "";

        table_ = "";

        primaryKey_ = "";

        operation_ = 0;

        time_ = 0L;

        internalGetMutableKvs().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kanven.conveyor.entity.RowEntityProto.internal_static_com_kanven_conveyor_entity_RowEntity_descriptor;
      }

      public com.kanven.conveyor.entity.RowEntityProto.RowEntity getDefaultInstanceForType() {
        return com.kanven.conveyor.entity.RowEntityProto.RowEntity.getDefaultInstance();
      }

      public com.kanven.conveyor.entity.RowEntityProto.RowEntity build() {
        com.kanven.conveyor.entity.RowEntityProto.RowEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kanven.conveyor.entity.RowEntityProto.RowEntity buildPartial() {
        com.kanven.conveyor.entity.RowEntityProto.RowEntity result = new com.kanven.conveyor.entity.RowEntityProto.RowEntity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.db_ = db_;
        result.table_ = table_;
        result.primaryKey_ = primaryKey_;
        result.operation_ = operation_;
        result.time_ = time_;
        result.kvs_ = internalGetKvs();
        result.kvs_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kanven.conveyor.entity.RowEntityProto.RowEntity) {
          return mergeFrom((com.kanven.conveyor.entity.RowEntityProto.RowEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kanven.conveyor.entity.RowEntityProto.RowEntity other) {
        if (other == com.kanven.conveyor.entity.RowEntityProto.RowEntity.getDefaultInstance()) return this;
        if (!other.getDb().isEmpty()) {
          db_ = other.db_;
          onChanged();
        }
        if (!other.getTable().isEmpty()) {
          table_ = other.table_;
          onChanged();
        }
        if (!other.getPrimaryKey().isEmpty()) {
          primaryKey_ = other.primaryKey_;
          onChanged();
        }
        if (other.getOperation() != 0) {
          setOperation(other.getOperation());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        internalGetMutableKvs().mergeFrom(
            other.internalGetKvs());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kanven.conveyor.entity.RowEntityProto.RowEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kanven.conveyor.entity.RowEntityProto.RowEntity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object db_ = "";
      /**
       * <code>optional string db = 1;</code>
       */
      public java.lang.String getDb() {
        java.lang.Object ref = db_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          db_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string db = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDbBytes() {
        java.lang.Object ref = db_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          db_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string db = 1;</code>
       */
      public Builder setDb(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        db_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string db = 1;</code>
       */
      public Builder clearDb() {
        
        db_ = getDefaultInstance().getDb();
        onChanged();
        return this;
      }
      /**
       * <code>optional string db = 1;</code>
       */
      public Builder setDbBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        db_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object table_ = "";
      /**
       * <code>optional string table = 2;</code>
       */
      public java.lang.String getTable() {
        java.lang.Object ref = table_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          table_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string table = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTableBytes() {
        java.lang.Object ref = table_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          table_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string table = 2;</code>
       */
      public Builder setTable(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        table_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string table = 2;</code>
       */
      public Builder clearTable() {
        
        table_ = getDefaultInstance().getTable();
        onChanged();
        return this;
      }
      /**
       * <code>optional string table = 2;</code>
       */
      public Builder setTableBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        table_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object primaryKey_ = "";
      /**
       * <code>optional string primaryKey = 3;</code>
       */
      public java.lang.String getPrimaryKey() {
        java.lang.Object ref = primaryKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          primaryKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string primaryKey = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPrimaryKeyBytes() {
        java.lang.Object ref = primaryKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          primaryKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string primaryKey = 3;</code>
       */
      public Builder setPrimaryKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        primaryKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string primaryKey = 3;</code>
       */
      public Builder clearPrimaryKey() {
        
        primaryKey_ = getDefaultInstance().getPrimaryKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string primaryKey = 3;</code>
       */
      public Builder setPrimaryKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        primaryKey_ = value;
        onChanged();
        return this;
      }

      private int operation_ ;
      /**
       * <code>optional int32 operation = 4;</code>
       */
      public int getOperation() {
        return operation_;
      }
      /**
       * <code>optional int32 operation = 4;</code>
       */
      public Builder setOperation(int value) {
        
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 operation = 4;</code>
       */
      public Builder clearOperation() {
        
        operation_ = 0;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>optional int64 time = 5;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional int64 time = 5;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 time = 5;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> kvs_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetKvs() {
        if (kvs_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              KvsDefaultEntryHolder.defaultEntry);
        }
        return kvs_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableKvs() {
        onChanged();;
        if (kvs_ == null) {
          kvs_ = com.google.protobuf.MapField.newMapField(
              KvsDefaultEntryHolder.defaultEntry);
        }
        if (!kvs_.isMutable()) {
          kvs_ = kvs_.copy();
        }
        return kvs_;
      }

      public int getKvsCount() {
        return internalGetKvs().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; kvs = 6;</code>
       */

      public boolean containsKvs(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetKvs().getMap().containsKey(key);
      }
      /**
       * Use {@link #getKvsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getKvs() {
        return getKvsMap();
      }
      /**
       * <code>map&lt;string, string&gt; kvs = 6;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getKvsMap() {
        return internalGetKvs().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; kvs = 6;</code>
       */

      public java.lang.String getKvsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetKvs().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; kvs = 6;</code>
       */

      public java.lang.String getKvsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetKvs().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearKvs() {
        getMutableKvs().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; kvs = 6;</code>
       */

      public Builder removeKvs(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableKvs().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableKvs() {
        return internalGetMutableKvs().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; kvs = 6;</code>
       */
      public Builder putKvs(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableKvs().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; kvs = 6;</code>
       */

      public Builder putAllKvs(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableKvs().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.kanven.conveyor.entity.RowEntity)
    }

    // @@protoc_insertion_point(class_scope:com.kanven.conveyor.entity.RowEntity)
    private static final com.kanven.conveyor.entity.RowEntityProto.RowEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kanven.conveyor.entity.RowEntityProto.RowEntity();
    }

    public static com.kanven.conveyor.entity.RowEntityProto.RowEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RowEntity>
        PARSER = new com.google.protobuf.AbstractParser<RowEntity>() {
      public RowEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RowEntity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RowEntity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RowEntity> getParserForType() {
      return PARSER;
    }

    public com.kanven.conveyor.entity.RowEntityProto.RowEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kanven_conveyor_entity_RowEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kanven_conveyor_entity_RowEntity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kanven_conveyor_entity_RowEntity_KvsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kanven_conveyor_entity_RowEntity_KvsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017RowEntity.proto\022\032com.kanven.conveyor.e" +
      "ntity\"\304\001\n\tRowEntity\022\n\n\002db\030\001 \001(\t\022\r\n\005table" +
      "\030\002 \001(\t\022\022\n\nprimaryKey\030\003 \001(\t\022\021\n\toperation\030" +
      "\004 \001(\005\022\014\n\004time\030\005 \001(\003\022;\n\003kvs\030\006 \003(\0132..com.k" +
      "anven.conveyor.entity.RowEntity.KvsEntry" +
      "\032*\n\010KvsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001B\020B\016RowEntityProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_kanven_conveyor_entity_RowEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kanven_conveyor_entity_RowEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kanven_conveyor_entity_RowEntity_descriptor,
        new java.lang.String[] { "Db", "Table", "PrimaryKey", "Operation", "Time", "Kvs", });
    internal_static_com_kanven_conveyor_entity_RowEntity_KvsEntry_descriptor =
      internal_static_com_kanven_conveyor_entity_RowEntity_descriptor.getNestedTypes().get(0);
    internal_static_com_kanven_conveyor_entity_RowEntity_KvsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kanven_conveyor_entity_RowEntity_KvsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
